# Generated by Django 3.2.2 on 2021-05-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.PositiveIntegerField(db_index=True, default=1)),
                ('email', models.EmailField(db_index=True, default='', max_length=254)),
                ('environment', models.CharField(db_index=True, default='', max_length=255)),
                ('component', models.CharField(db_index=True, default='', max_length=255)),
                ('message', models.CharField(default='', max_length=255)),
                ('data_payload', models.JSONField()),
            ],
        ),
    ]
