# Generated by Django 3.2.2 on 2021-05-08 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('email', models.CharField(max_length=255)),
                ('environment', models.CharField(max_length=255)),
                ('component', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
                ('dataPayload', models.TextField()),
            ],
        ),
    ]
