# Generated by Django 3.2.2 on 2021-05-08 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_eventtimestamped'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventTimeStamped',
        ),
    ]
